version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
          name: Pushing Deploy Script
          command: scp -oStrictHostKeyChecking=no deploy.sh $DEPLOY_CREDENTIALS:/tmp/deploy.sh
      - run:
          name: Setting Deploy Script Permissions
          command: ssh -oStrictHostKeyChecking=no -v $DEPLOY_CREDENTIALS "chmod +x /tmp/deploy.sh"
  install-prod:
    docker:
      - image: cimg/base:2022.03
    steps:
      - run:
          name: Executing Deploy
          command: ssh -oStrictHostKeyChecking=no -v $DEPLOY_CREDENTIALS "/tmp/deploy.sh"
  install-stage:
    docker:
      - image: cimg/base:2022.03
    steps:
      - run:
          name: Executing Deploy
          command: ssh -oStrictHostKeyChecking=no -v $DEPLOY_CREDENTIALS "/tmp/deploy.sh $CIRCLE_BRANCH"


# Orchestrate our job run sequence
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - pull-and-build
      - install-prod:
          filters:
            branches:
              only:
                - main
          requires:
            - pull-and-build
      - install-stage:
          requires:
            - pull-and-build
